######################## default configuration ####################
baseURL = "https://www.materiguru.github.io"
theme = "mundanem"
title = "MATERI GURU"
MetaDataFormat = "yaml"
themesDir = "themes"
enableRobotsTXT = true
summaryLength = 20
rssLimit = 30
buildFuture = true
copyright = "Copyright 2021 [materiguru.github.io](https://materiguru.github.io)"

# uglyurls = true
# paginate = 6
# buildFuture = true
# Shortname disqus, silahkan sesuaikan
# DisqusShortname = "duniasosial"
# Untuk Google Analytic, silahkan sesuikan
# googleAnalytics = "UA-XXXX" 
# Untuk deskripsi tag meta di homepage
# description = "Portal Web Informasi Pendidikan Indonesia"

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML", "RSS"]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[frontmatter]
    date = ["publishDate", "date", ":default"]

[Params]
   hold = "/img/placeholder.svg"
   logo = "/logo.png"
   description = "Portal Web Informasi Pendidikan Indonesia"
 

[permalinks]
  "post" = "/:filename"

# disableKinds = ["taxonomy", "taxonomyTerm"]
# disableKinds = ["tags", "term"]
[Taxonomies]
    tag = "categories"
    category = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[markup]
  defaultMarkdownHandler = "goldmark"
#  [markup.asciidocExt]
#    backend = "html5"
#    extensions = []
#    failureLevel = "fatal"
#    noHeaderOrFooter = true
#    preserveTOC = false
#    safeMode = "unsafe"
#    sectionNumbers = false
#    trace = false
#    verbose = false
#    workingFolderCurrent = false
#    [markup.asciidocExt.attributes]
#  [markup.blackFriday]
#    angledQuotes = false
#    footnoteAnchorPrefix = ""
#    footnoteReturnLinkContents = ""
#    fractions = true
#    hrefTargetBlank = false
#    latexDashes = true
#    nofollowLinks = false
#    noreferrerLinks = false
#    plainIDAnchors = true
#    skipHTML = false
#    smartDashes = true
#    smartypants = true
#    smartypantsQuotesNBSP = false
#    taskLists = true
#  [markup.tableOfContents]
#    endLevel = 4
#    ordered = false
#    startLevel = 3
  [markup.goldmark.renderer]
    unsafe = true
    enableInlineShortcodes = true

# Biodata Author
[author]
    name = "Gabrilugo"
    homepage = "/"
    image = "/img/logo.svg"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[minify]
    [minify.tdewolff.html]
      keepQuotes = true
